### ISSUE TITLE
QuestName="Journey to Thrallmar" QuestId="10289"

### ISSUE THREAD

**Issue by VoidtechX** [EchoTiger/NewQuestingPack#10]
If quest "Journey to Thrallmar" in hellfire is done by hand, bot don't recognize that and goes to questigiver, stuck on waiting to pick up quest. If this quest is done by bot, everything works well

**Comment by EchoTiger** [comment]
'Journey to Thrallmar' seems to be a breadcrumb quest along with 'Arrival in Outland'
If you do 'Report to Nazgrel' before doing these quests, then the two above quests will become unavailable.

I've added a check to 'Journey to Thrallmar' and 'Arrival in Outland' which prevents them from running if 'Report to Nazgrel' is complete.

**Comment by EchoTiger** [comment]
Fixed in https://github.com/EchoTiger/NewQuestingPack/commit/1ccb70ea777a1e18001fc11cea5448d8572d99f3
