### ISSUE TITLE
Q12213  Horde - Dragonblight :  Quest objective actions are missing 

### ISSUE THREAD

**Issue by marrvin2** [EchoTiger/NewQuestingPack#11]
The "quest objective action" for quest   12213 is missing.
Only PickUp and TurnIn exists. Leading to a "stop"  when trying to turn in that quest,
I copied the old code from old pack to make it continue .

 

  <If Condition="HasQuest(12213) &amp;&amp; !IsObjectiveComplete(3,12213)">
        <CustomBehavior File="FlyTo" X="3930.799" Y="-2600.958" Z="206.5849" />
        <CustomBehavior File="ForcedDismount" />
        <While Condition="HasQuest(12213) &amp;&amp; !IsObjectiveComplete(3,12213)">
          <UseItem ItemId="37173" QuestId="12213" X="3979.872" Y="-2706.403" Z="164.8311" />
        </While>
      </If>
      <If Condition="HasQuest(12213) &amp;&amp; !IsObjectiveComplete(2,12213)">
        <CustomBehavior File="FlyTo" X="3763.256" Y="-2927.972" Z="272.3773" />
        <CustomBehavior File="FlyTo" X="3813.463" Y="-2866.828" Z="219.7106" />
        <CustomBehavior File="ForcedDismount" />
        <While Condition="HasQuest(12213) &amp;&amp; !IsObjectiveComplete(2,12213)">
          <UseItem ItemId="37173" QuestId="12213" X="3910.563" Y="-2803.458" Z="175.3991" />
        </While>
      </If>
      <If Condition="HasQuest(12213) &amp;&amp; !IsObjectiveComplete(1,12213)">
        <CustomBehavior File="FlyTo" X="3776.277" Y="-3206.204" Z="338.3256" />
        <CustomBehavior File="FlyTo" X="3710.701" Y="-3242.004" Z="280.81" />
        <CustomBehavior File="ForcedDismount" />
        <While Condition="HasQuest(12213) &amp;&amp; !IsObjectiveComplete(1,12213)">
          <UseItem ItemId="37173" QuestId="12213" X="3603.475" Y="-3268.788" Z="222.2524" />
        </While>
      </If>

**Comment by EchoTiger** [comment]
Fixed in https://github.com/EchoTiger/NewQuestingPack/commit/1736d5a6927dd76611437c1766e638ddc2b23dc4
