### ISSUE TITLE
"Creature Comforts" (http://wowhead.com/quest=12599)

### ISSUE THREAD

**Issue by VoidtechX** [EchoTiger/NewQuestingPack#12]
`Goal: InteractWith-7b5abb: "Creature Comforts" (http://wowhead.com/quest=12599)
Interacting with MobId(190543)
    [Ref: "Zul'Drak ($Rev: 6041 $)" @line   ##519]`

Bot keeps flying between hotspots, not interacting with "Dread Thornwoods"
[16836 2017-05-22 10.47.txt](https://github.com/EchoTiger/NewQuestingPack/files/1018650/16836.2017-05-22.10.47.txt)

**Comment by EchoTiger** [comment]
Added more object IDs for the "Dread Thornwoods" on commit https://github.com/EchoTiger/NewQuestingPack/commit/b188f27ff75aae24c95ecd16dcf646a30a03bc4f
