### ISSUE TITLE
"The Denouncement" (http://www.wowhead.com/quest=12273/the-denouncement)

### ISSUE THREAD

**Issue by VoidtechX** [EchoTiger/NewQuestingPack#13]
Bot is trying to interract with "Commander Jordan" trough walls
![wowscrnshot_052217_151745](https://cloud.githubusercontent.com/assets/28795726/26310644/e1303c10-3f01-11e7-8fff-4ae4d33f7581.jpg)
[3412 2017-05-22 15.12.txt](https://github.com/EchoTiger/NewQuestingPack/files/1018931/3412.2017-05-22.15.12.txt)

**Comment by EchoTiger** [comment]
Fixed in https://github.com/EchoTiger/NewQuestingPack/commit/7ee98e81a1d3c2b25ecf7a7c8015d7507741adef
