### ISSUE TITLE
"Emerald Dragon Tears" (http://wowhead.com/quest=12200)

### ISSUE THREAD

**Issue by VoidtechX** [EchoTiger/NewQuestingPack#14]
Goal: InteractWith-7b5abb: "Emerald Dragon Tears" (http://wowhead.com/quest=12200)
Interacting with Emerald Dragon Tear, MobId(1886461)
    [Ref: "Dragonblight ($Rev: 6041 $)" @line 241]

Similiar case that reported 2 hours ago, bot stuck on flying between hotspots. Only gather quest items when random mob is on bot path and dismount him. 
[5660 2017-05-22 15.10.txt](https://github.com/EchoTiger/NewQuestingPack/files/1019015/5660.2017-05-22.15.10.txt)

**Comment by EchoTiger** [comment]
The profile seems to cover all IDs of the objects in question - and the hotspots look fine to me.
This will need to be investigated further as I don't see anything wrong in the code itself.

**Comment by EchoTiger** [comment]
I've had several testers go through here and I hadn't noticed an issue, so I'm closing this.
However, I will continue to keep my eye out on this quest to see if anything strange happens.
