### ISSUE TITLE
Setting the Stage" (http://wowhead.com/quest=12672)

### ISSUE THREAD

**Issue by VoidtechX** [EchoTiger/NewQuestingPack#15]
`Goal:` InteractWith-7b5abb: "Setting the Stage" (http://wowhead.com/quest=12672)
Interacting with MobId(190717), Underworld Power Fragment
    [Ref: "Zul'Drak ($Rev: 6041 $)" @line 833]`

At start bot works well on this quest, but at some point gets in loop flying  between hotspots
[16292 2017-05-22 13.53.txt](https://github.com/EchoTiger/NewQuestingPack/files/1019044/16292.2017-05-22.13.53.txt)

**Comment by EchoTiger** [comment]
"Interacting with MobId(190717)" is a bit strange considering when I coded this quest, I set it up to interact with 190717 and 109719.

After checking it, I've also added 109718.
The current version of the profiles on https://github.com/EchoTiger/NewQuestingPack/commit/f073ccd8ad5808981dca646372e360818308a02d should fix this.
