### ISSUE TITLE
"Once More Unto The Breach" (http://www.wowhead.com/quest=13105)

### ISSUE THREAD

**Issue by VoidtechX** [EchoTiger/NewQuestingPack#16]
`Goal: Picking up quest with ID Once More Unto The Breach, Hero [Ref: "Pickup" @line 211]`

Bot keeps opening and closing quest frame, after taking quest by hand still want to pickup from npc
[11500 2017-05-22 16.06.txt](https://github.com/EchoTiger/NewQuestingPack/files/1019096/11500.2017-05-22.16.06.txt)

**Comment by marrvin2** [comment]
haha...this minute I encountered this issue  myself and came here to report it, so I will hijacking your ticket :smile_cat: 
This Icecrown quest (Alliance  ID = 13104)  has diffenrent QuestID for Horde (=13105)

@Nentor77:  just change 13104 into 13105  at Line 211/212

**Comment by EchoTiger** [comment]
QuestID-13104 is for Alliance and Horde.
QuestID-13105 is for Death Knight.

Fixed in https://github.com/EchoTiger/NewQuestingPack/commit/3c37ee9be4d077f661b34b44c471fce492f0bf96
