### ISSUE TITLE
Nagrand - Bugs

### ISSUE THREAD

**Issue by bartolije** [EchoTiger/NewQuestingPack#18]
The char keep flying between hotspot, without killing unit, or reach any final destinations.

Info tabs:
```Goal: KillUntilComplete-7b5abb: In Progress (no associated quest)    [Ref: "Nagrand ($Rev: 6041 $)" @line 179]```
[4108_2017-05-22_18.07.txt](https://github.com/EchoTiger/NewQuestingPack/files/1022257/4108_2017-05-22_18.07.txt)

**Comment by EchoTiger** [comment]
Do you know if you had the item(or quest) "Howling Wind" ?

Quest: http://www.wowhead.com/quest=9861/the-howling-wind
Item: http://www.wowhead.com/item=24504/howling-wind

The kill logic at line 179 should terminate when you have the item or quest and when you collect three of item: "Pair of Ivory Tusks"

**Comment by bartolije** [comment]
Can't help on this, manually passed all quest to avoid this.
Next char incomming on this zone, we'll see
