### ISSUE TITLE
Q27982 - Searing Gorge

### ISSUE THREAD

**Issue by bartolije** [EchoTiger/NewQuestingPack#2]
The bot keep moving between the 2 zone where mob to kill are.

Info tab:
```
Goal: KillUntilComplete-7b5abb: "Les colliers du Crépuscule" (http://wowhead.com/quest=27982)
    [Ref: "Searing Gorge ($Rev: 6041 $)" @line 353]
```
[5596 2017-05-13 23.23.txt](https://github.com/EchoTiger/NewQuestingPack/files/998979/5596.2017-05-13.23.23.txt)

**Comment by EchoTiger** [comment]
Were there no mobs spawned in the area?
The farm spot for this location is quite small, and if all the mobs are dead it will run between the hotspots looking for them.

**Comment by bartolije** [comment]
Nope. Mob was there, on both zone.
The bot just kept going on both hotspot, and as soon as he was on on of them, goes to the second.
(Needed to do the quest manually)

**Comment by EchoTiger** [comment]
So there was mobs all around and the bot wasn't attacking them?

Your log is showing it attacking them, and there doesn't really seem to be anything wrong with the code itself - it has every ID for the mobs in the area.

**Comment by bartolije** [comment]
But definitively no looting them, since it's the purpose of the quest.
I'm 100% sure about this, and gonna give another try, to get fresh log
about this quest

**Comment by EchoTiger** [comment]
Closing for now.
