### ISSUE TITLE
Autoloader fails on Goblin Death Knight after DK Starting Zone finished

### ISSUE THREAD

**Issue by marrvin2** [EchoTiger/NewQuestingPack#29]
The Autoloader 1-110  tries to load  Goblin Starter Profile after Death Knight Starter Profile is finished because the didn't complete Q25267

```
<If Condition="Me.Race == WoWRace.Goblin &amp;&amp; !IsQuestCompleted(25267)" >
	<Code File="LoadProfile" ProfileName="Horde\Starters\Goblin.xml" RememberProfile="true" />
</If>
```
so an addition test for class DK  is needed ;)

**Comment by EchoTiger** [comment]
Fixed in https://github.com/EchoTiger/NewQuestingPack/commit/255a9239c8d1251797c9fa7611efe847b8f18844
