### ISSUE TITLE
Q27979 - NoViableMob

### ISSUE THREAD

**Issue by bartolije** [EchoTiger/NewQuestingPack#3]
Hello,

On Quest 27979, the bot stop move on a rock, keep saying they are no mobs to kill.
Which seems true, since the bot isn't in the right zone at all.

Info tab:
```
Goal: KillUntilComplete-7b5abb: "Les colliers du Crépuscule" (http://wowhead.com/quest=27982)
    [Ref: "Searing Gorge ($Rev: 6041 $)" @line 353]
```
[5596 2017-05-13 23.23.txt](https://github.com/EchoTiger/NewQuestingPack/files/999150/5596.2017-05-13.23.23.txt)

**Comment by EchoTiger** [comment]
This duplicates #2
