### ISSUE TITLE
Horde barrens quest - interact issue?

### ISSUE THREAD

**Issue by dh-mmo** [EchoTiger/NewQuestingPack#32]
[3404 2017-06-05 16.18.txt](https://github.com/EchoTiger/NewQuestingPack/files/1052787/3404.2017-06-05.16.18.txt)
https://puu.sh/wbLKg/9655583182.png

**Comment by EchoTiger** [comment]
Looks like it's trying to ride the kodo but the game client is declining because you cannot do this while in Travel Form / Shapeshift.

I've added a code to remove Travel Form / Shapeshift in commit https://github.com/EchoTiger/NewQuestingPack/commit/3828825d1782313a3091ff7fcfaf41cae78fddba
