### ISSUE TITLE
Stuck at lvl 50 - sanity problem? check log

### ISSUE THREAD

**Issue by dh-mmo** [EchoTiger/NewQuestingPack#35]
![vmware_2017-06-06_15-26-33](https://cloud.githubusercontent.com/assets/28988584/26831677/546178b2-4acd-11e7-873d-49f8be9f6965.png)

[7620 2017-06-06 12.38.txt](https://github.com/EchoTiger/NewQuestingPack/files/1055147/7620.2017-06-06.12.38.txt)

works after i deleted assembly folder...weird.

**Comment by EchoTiger** [comment]
This was already fixed for the Alliance profiles - the changes were still pending for Horde.
Fixed on https://github.com/EchoTiger/NewQuestingPack/commit/d50dcaf12a6531037ad683c680984c9a960102d7
