### ISSUE TITLE
Error with Profile, Honorbuddy Stops

### ISSUE THREAD

**Issue by Cryopier** [EchoTiger/NewQuestingPack#38]
> [Function Engine] Main pulse shut down.  All functions have been deactivated.
4 compiler errors encountered in profile 'Stormheim ($Rev: 6126 $)'
'Code' xml element on line number 1478 has following errors with code: 
					private static void IncludeEmpoweredRunestoneUnits()
					{
						Targeting.Instance.IncludeTargetsFilter += IncludeEmpoweredRunestoneUnitsFilter;
						BotEvents.OnBotStopped += BotEvents_OnBotStopped;
					}
					private static void StopIncludeEmpoweredRunestoneUnits()
					{
						Targeting.Instance.IncludeTargetsFilter -= IncludeEmpoweredRunestoneUnitsFilter;
						BotEvents.OnBotStopped -= BotEvents_OnBotStopped;
					}
					private static void IncludeEmpoweredRunestoneUnitsFilter(List<WoWObject> incomingUnits, HashSet<WoWObject> outgoingUnits)
					{
						foreach (var unit in incomingUnits)
						{
							if (unit is WoWUnit && (unit.Entry == 97223 || unit.Entry == 97221))
								outgoingUnits.Add(unit);
						}
					}
				
	1) The name 'BotEvents_OnBotStopped' does not exist in the current context at line 4

	2) The name 'BotEvents_OnBotStopped' does not exist in the current context at line 9

'Code' xml element on line number 1704 has following errors with code: 
					private static void IncludeFelskornChannelers()
					{
						Targeting.Instance.IncludeTargetsFilter += IncludeFelskornChannelersFilter;
						BotEvents.OnBotStopped += BotEvents_OnBotStopped;
					}
					private static void StopIncludeFelskornChannelers()
					{
						Targeting.Instance.IncludeTargetsFilter -= IncludeFelskornChannelersFilter;
						BotEvents.OnBotStopped -= BotEvents_OnBotStopped;
					}
					private static void IncludeFelskornChannelersFilter(List<WoWObject> incomingUnits, HashSet<WoWObject> outgoingUnits)
					{
						foreach (var unit in incomingUnits)
						{
							if (unit is WoWUnit && unit.Entry == 96489)
								outgoingUnits.Add(unit);
						}
					}
				
	1) The name 'BotEvents_OnBotStopped' does not exist in the current context at line 4

	2) The name 'BotEvents_OnBotStopped' does not exist in the current context at line 9

Bot stopping! Reason: None Given

**Comment by EchoTiger** [comment]
Fixed in https://github.com/EchoTiger/NewQuestingPack/commit/50d4294d09fd8e9940dd2c50e315150f1d5a334d
Thanks!
