### ISSUE TITLE
Q25695 - Bot canno't do the quest

### ISSUE THREAD

**Issue by bartolije** [EchoTiger/NewQuestingPack#4]
Hello,

On quest 25695, the bot doesn't seems able to do the quest.
It keep beeing spotted, and so, fail the mission.

Info tab:
`Goal: Moving to <-11807.82, -3231.535, -30.10377> [Ref: "MoveTo" @line 335]`

To succeed the mission, it would be much more efficient to go at the exact position: 
<X="-11803.88" Y="-3233.858" Z="-28.4361" />

http://i.imgur.com/qHl4Ydi.png

**Comment by EchoTiger** [comment]
I've made improvements to this quest in. https://github.com/EchoTiger/NewQuestingPack/commit/969e7df8345c22003e3b2d258f4c21edcc4f0b93, it will now stand in the back of the cart. However it will still fail several times before it can be completed.

I originally wrote detection of which way the guards were standing/facing, but even then it didn't work too well - so the best solution is to just brute force it.
