### ISSUE TITLE
terrokar Q 10037

### ISSUE THREAD

**Issue by dh-mmo** [EchoTiger/NewQuestingPack#40]
Goal: KillUntilComplete-7b5abb: "Ich würd' lieber angeln" (http://wowhead.com/quest=10037)
    [Ref: "Terrokar Forest ($Rev: 6041 $)" @line 213]

lots of navigation issues inside the lake
[6548 2017-06-07 09.19.txt](https://github.com/EchoTiger/NewQuestingPack/files/1057481/6548.2017-06-07.09.19.txt)

**Comment by EchoTiger** [comment]
This is a noted issue that may not entirely be fixable on the profile level.
Honorbuddy in general has a lot of issues with water-based navigation.

The best solution is to just remove this quest from the profile.

**Comment by EchoTiger** [comment]
Removed in https://github.com/EchoTiger/NewQuestingPack/commit/b49066a39ae029ddf229168132a2253315a9fe5e
