### ISSUE TITLE
Infinite loop Goal: Turning in Quest - Буря на взморье (http://wowhead.com/quest=25177) : To - Gar'Thok : ID - 3139 [Ref: "Turnin" @line 274]

### ISSUE THREAD

**Issue by nahhets** [EchoTiger/NewQuestingPack#41]
[3684 2017-06-08 03.04.txt](https://github.com/EchoTiger/NewQuestingPack/files/1058636/3684.2017-06-08.03.04.txt)

**Comment by EchoTiger** [comment]
It was a minor logical error.
Fixed in https://github.com/EchoTiger/NewQuestingPack/commit/818d142bcddfa9c20e367d15027705a3410d63a9
