### ISSUE TITLE
Quest 12882

### ISSUE THREAD

**Issue by dh-mmo** [EchoTiger/NewQuestingPack#44]
Goal: Turning in Quest - Uralte Relikte (http://wowhead.com/quest=12882) : To - Olut Alegut : ID - 30472 [Ref: "Turnin" @line 745]

[6864 2017-06-08 15.16.txt](https://github.com/EchoTiger/NewQuestingPack/files/1061153/6864.2017-06-08.15.16.txt)

toon has no reliks. happens also after abandoning the quest.
no reliks under the last sold items. dunno if he had some and sold them.
bought some from ah. worked.

**Comment by EchoTiger** [comment]
Added protection of Relic of Ulduar from the "AFK Mode" sell logic in https://github.com/EchoTiger/NewQuestingPack/commit/a7a355091abd69f6f1875dfafcdee8520e6319d7
