### ISSUE TITLE
Relics and Cooking Receipes sold on "vendor run".

### ISSUE THREAD

**Issue by marrvin2** [EchoTiger/NewQuestingPack#47]
This was after dying,  and I am not sure if it is actually related to New Questing Pack.
After corpse pickup my toon started a "vendor  run" by summoning vendor mount and sold   soulbound relics  (with higher iLevel than equipped) and also an unlearned cooking recepipe.

AFK Mode was disabled in Profile Config.

**Comment by EchoTiger** [comment]
If AFK mode was disabled, then the bot itself sold the relics/recipes.
AFK mode is the only thing that affects the sell logic of Honorbuddy.

**Comment by marrvin2** [comment]
yeah... I thouth that too, because the "vendor run" text color message was plain "white"  ;-)
ok... I will report this as a vendoring "bug" at the forums.
you may close this this issue here.
