### ISSUE TITLE
Quest 12756 on DeathKnight-Starter:  stuck entering house to turn in quest

### ISSUE THREAD

**Issue by marrvin2** [EchoTiger/NewQuestingPack#49]
I made a new tauren DK this morning after updating NQP   (pronnounced  "Nuke P" xD   )

everything went smooth until turn in of Quest: The Scarlet Onslaught Emerges (http://wowhead.com/quest=12756)

The char was **mounted**  and in **scarlet disguise** and tried to enter the house with the questgiver at 
`<Hotspot X="1405.048" Y="-5822.889" Z="131.3622" />`
it did NOT dismount when trying to enter the door to the house at that hotspot.

Unfortunatley  the Disguise Aura cannot be cancelled.  So I dismounted by hand in front of the house to continue the profile.

**Profile Config**:  I had Anti-Stuck  enabled, but not AFK Mode.

**Log:**
[2200 2017-06-19 11.04.txt.zip](https://github.com/EchoTiger/NewQuestingPack/files/1084660/2200.2017-06-19.11.04.txt.zip)

-- marrvin

**Comment by EchoTiger** [comment]
The bot's navigation system should automatically dismount the player if it detects it is running into a doorway.  
So this isn't profile related at all,  however I will add in a dismount at the doorway as a temporary work around.

Added in https://github.com/EchoTiger/NewQuestingPack/commit/a7c9584d723886e0eff8202c7f92a6b355890092

**Comment by marrvin2** [comment]
thank you
