### ISSUE TITLE
Q10208  Code flow error Horde/Outland/Hellfire PI  (fix inside :D  )

### ISSUE THREAD

**Issue by marrvin2** [EchoTiger/NewQuestingPack#5]
Currently after collection the Portal Stones inb Hellfire Peninsular the bot stops doing nothing.

I have checked the source and moved the two "InteractWith" MobId="184290"  ..  statements inside the "while DoQuest(10208)" loop  after  KillUntilComplete 

That fixed it.

**Comment by EchoTiger** [comment]
Fixed with commit #120 https://github.com/EchoTiger/NewQuestingPack/commit/bb9b9aca2173da1b69ea770d371507c0512e9eac
