### ISSUE TITLE
Q9770 & Q9899  Horde/Zangamarsh  improvment/speedup

### ISSUE THREAD

**Issue by marrvin2** [EchoTiger/NewQuestingPack#6]
Currently the profile waits  a long time for named Mob Sporewing to spawn/appear at his spawnpoint , when infact this Mob is roaming the same area as the other sporebats needed for Q9770 - see http://www.wowhead.com/npc=18280/sporewing#map

So best is to flip the two KillUntilComplete to first Kill 10 Sporebats and include Sporewing in the PursuitList for Q9770 

If we did not get the Sporewing we then camp his spawnpoint.
Like this:

		<Code File="KillUntilComplete" MobIds="18130, 18280" QuestId="9770" >
			<HuntingGrounds>
				<Hotspot X="443.0681" Y="5852.621" Z="23.41469" />
				<Hotspot X="297.5428" Y="5832.962" Z="19.27119" />
				<Hotspot X="179.4271" Y="5694.528" Z="22.1513" />
				<Hotspot X="270.0659" Y="5583.489" Z="23.93551" />
				<Hotspot X="241.7077" Y="5227.238" Z="21.89751" />
				<Hotspot X="332.4232" Y="5161.003" Z="20.99276" />
			</HuntingGrounds>
		</Code>
		<Code File="KillUntilComplete" MobId="18280" QuestId="9899" X="409.2992" Y="5618.349" Z="19.84682" />

**Comment by EchoTiger** [comment]
Thanks for the recommendation, the new code is now changed on commit https://github.com/EchoTiger/NewQuestingPack/commit/6e1336bb080109926d61da931713d6c45c16ffa7
