### ISSUE TITLE
[Monk] Can't pickup quest - missing npc

### ISSUE THREAD

**Issue by bartolije** [EchoTiger/NewQuestingPack#65]
Goal: Picking up quest with ID Barrier to Entry [Ref: "Pickup" @line 128]

The NPC isn't there, and the bot is waiting for him
[9256 2017-06-29 07.24.txt](https://github.com/EchoTiger/NewQuestingPack/files/1110965/9256.2017-06-29.07.24.txt)

http://i.imgur.com/534LWQ3.jpg

**Comment by EchoTiger** [comment]
Perhaps the breadcrumb to "activate" this zone can be picked up via the adventure journal.

**Comment by bartolije** [comment]
I confirm it is fixed by picked the quest throught adventure journal.
Did this manually, all went fine after
