### ISSUE TITLE
Lvling human rogue. At around 21 lvl.

### ISSUE THREAD

**Issue by kornel-filep** [EchoTiger/NewQuestingPack#67]
So Im trying to lvl a rogue. And the bot always goes wrong after like 1-2 lvls.
Logs.

https://drive.google.com/file/d/0B_24hqqLu6UiQzAzdUdpc3Q3RkE/view?usp=sharing

Cannot attach the logfile to github cuz its too damn big.

**Comment by EchoTiger** [comment]
You're getting issues not related to the profiles at all.
The bot is having problems reading memory from the game.

Try using DirectX9 instead.
If that doesn't work, you'll need to report it to the forum for Tony to look at.
