### ISSUE TITLE
Undead Rogue not Level 5 at end of Starter Profile

### ISSUE THREAD

**Issue by marrvin2** [EchoTiger/NewQuestingPack#9]
My Undead Rogue (not a single Heirloom) was only  Level 4.9  after profile finished leading in a "autoloader" looping due to checkpoints.

I added the Delivery Quest back to end of the profile to get that extra XP.
No big deal, as the rogue is passing the TurnIn NPC on its way  to  undercity/orgrimmar.

<PickUp QuestName="Vital Intelligence" QuestId="24972" GiverName="Shadow Priest Sarvis" GiverId="1569" X="1842.81" Y="1635.517" Z="96.93334" />
<TurnIn QuestName="Vital Intelligence" QuestId="24972" TurnInName="Deathguard Simmer" TurnInId="1519"   X="2222.186" Y="1012.801" Z="37.12211"/>

fff  (furry fun fact): he then leveled to 5 just be exploring :D

**Comment by EchoTiger** [comment]
Fixed a few days ago in https://github.com/EchoTiger/NewQuestingPack/commit/6ef1a386f8f791aef867b43297ec292894ef6c98
